### ISSUE TITLE
Group.Groupinfo Inner Classe

### ISSUE THREAD

**Issue by Chrasonier** [comtel2000/fritz-home-skill#4]
Hey,

ich versuche ja aktuell die Heizkörperthermostate (inklusive Gruppenschaltung) zu implementieren. Leider hänge ich gerade ein bisschen fest bei der Inner Class Group.Groupinfo.
Ich möchte in getSwitchDevices() wo die Werte für die Gruppen zugewiesen werden auch die "masterdeviceid" und "members" zuweisen. Leider kriege ich den Zugriff auf die InnerClass nicht hin. Vielleicht kannst du mir helfen.
Mit 
`Group.Groupinfo info = new Group.Groupinfo();`
erstelle ich ein leeren Objekt, doch wie erstelle ich es für die aktuelle Gruppe?

Gruß
Tobi

**Comment by comtel2000** [comment]
Ich bin nicht sicher wofür du Groupinfo brauchst. Die Daten sollten hier aus der Fritzbox kommen und nicht selbst gesetzt werden. Trotzdem hier ein Bsp:
```java
    Group.Groupinfo info = new Group.Groupinfo();
    info.setMasterdeviceid(1);
    info.setMembers("2,3,4");
```
